In [1]:
import numpy as np
import pandas as pd

In [6]:
df = pd.read_csv("C:\\Users\\Student\\Desktop\\Ml programs B-section\\EXP_12\\play_tennis.csv")

In [7]:
df

    day   outlook  temp humidity    wind play
0    D1     Sunny   Hot     High    Weak   No
1    D2     Sunny   Hot     High  Strong   No
2    D3  Overcast   Hot     High    Weak  Yes
3    D4      Rain  Mild     High    Weak  Yes
4    D5      Rain  Cool   Normal    Weak  Yes
5    D6      Rain  Cool   Normal  Strong   No
6    D7  Overcast  Cool   Normal  Strong  Yes
7    D8     Sunny  Mild     High    Weak   No
8    D9     Sunny  Cool   Normal    Weak  Yes
9   D10      Rain  Mild   Normal    Weak  Yes
10  D11     Sunny  Mild   Normal  Strong  Yes
11  D12  Overcast  Mild     High  Strong  Yes
12  D13  Overcast   Hot   Normal    Weak  Yes
13  D14      Rain  Mild     High  Strong   No

In [8]:
df['play'].value_counts()

play
Yes    9
No     5
Name: count, dtype: int64

In [10]:
Pyes = 9/14
Pno =5/14
print(Pyes)
print(Pno)

0.6428571428571429
0.35714285714285715

In [11]:
crosstab_result = pd.crosstab(df['outlook'], df['play'])
reordered_result = crosstab_result[['Yes', 'No']]
print(reordered_result)

play      Yes  No
outlook
Overcast    4   0
Rain        3   2
Sunny       2   3

In [12]:
Pon =0
Prn=2/5
Psn=3/5
Poy=4/9
Pry=3/9
Psy=2/9

In [13]:
pd.crosstab(df['temp'],df['play'])

play  No  Yes
temp
Cool   1    3
Hot    2    2
Mild   2    4

In [14]:
Pcn=1/5
Phn=2/5
Pmn=2/5
Pcy=3/9
Phy=2/9
Pmy=4/9

In [15]:
pd.crosstab(df['humidity'],df['play'])

play      No  Yes
humidity
High       4    3
Normal     1    6

In [17]:
Pnh=4/5
Pnn=1/5
Pyh=3/9
Pyn=6/9

In [18]:
pd.crosstab(df['wind'],df['play'])

play    No  Yes
wind
Strong   3    3
Weak     2    6

In [19]:
Pns=3/5
Pnw=2/5
Pys=3/9
Pyw=6/9

In [20]:
PY = Psy*Pcy*Pyh*Pys*Pyes
PN = Psn*Pcn*Pnh*Pns*Pno
print(PY)
print(PN)
print('ans is',max(PN,PY))

0.005291005291005291
0.02057142857142857
ans is 0.02057142857142857